name: 清理Mihomo编译构建历史记录
on:
  # 每日凌晨2点自动清理
  schedule:
    - cron: '0 2 * * *'
  # 页面手动一键执行
  workflow_dispatch:

jobs:
  clean_build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 删除旧构建运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          # 保留最近10条构建记录，更早全部删除
          keep_minimum_runs: 10
          retain_days: 0
          workflow_name: "Build Mihomo armv7 for Linux 4.4 (Dispatch)"
