name: 清理Mihomo编译构建历史记录
on:
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch:
jobs:
  clean_build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 删除旧构建运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          keep_minimum_runs: 5
          retain_days: 0
          delete_workflow_pattern: "Build Mihomo armv7 for Linux 4.4 (Dispatch)"
